name: Deploy para Azure Web App

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu repositório

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Fazer deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: webapp-academia-50410
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
